option(ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)

if(ENABLE_ASAN OR ENABLE_UBSAN)
    if(MSVC)
        if(ENABLE_ASAN)
            add_compile_options(/fsanitize=address)
            add_link_options(/fsanitize=address)
        endif()
        if(ENABLE_UBSAN)
            message(WARNING "UBSAN is not supported with MSVC; ignoring ENABLE_UBSAN")
        endif()
    else()
        set(_sanitizers "")
        if(ENABLE_ASAN)
            list(APPEND _sanitizers address)
        endif()
        if(ENABLE_UBSAN)
            list(APPEND _sanitizers undefined)
        endif()
        string(REPLACE ";" "," _sanitizers_string "${_sanitizers}")
        add_compile_options(-fsanitize=${_sanitizers_string})
        add_link_options(-fsanitize=${_sanitizers_string})
    endif()
endif()
